select * from LG_217_ITEMS

select * from LG_217_CLCARD

select * from LG_217_01_STLINE

select count(*) from LG_217_01_STLINE

select TOP 1000

ITM.LOGICALREF,ITM.CODE,ITM.NAME,ITM.KEYWORD1 AS BRAND,ITM.KEYWORD2 AS CATEGORY1,ITM.KEYWORD3 AS CATEGORY2,
STL.DATE_,STL.AMOUNT,STL.PRICE,STL.LINENET,
STF.BRANCH,D.NAME AS SUBE

 from LG_217_ITEMS ITM

 LEFT JOIN LG_217_01_STLINE STL ON STL.STOCKREF=ITM.LOGICALREF
 LEFT JOIN LG_217_01_STFICHE STF ON STF.LOGICALREF=STL.STFICHEREF
 LEFT JOIN L_CAPIDIV D ON D.NR=STF.BRANCH AND D.FIRMNR=217

 WHERE STL.TRCODE=7


 UPDATE L_CAPIDIV SET NAME=REPLACE(NAME,'?','Ş')

 create view VM_SATISLAR
 as
 select 

 ITM.LOGICALREF,ITM.CODE,ITM.NAME,ITM.KEYWORD1 AS BRAND,ITM.KEYWORD2 AS CATEGORY1,ITM.KEYWORD3 AS CATEGORY2,
 STL.DATE_,STL.AMOUNT,STL.PRICE,STL.LINENET,
 STF.BRANCH,D.NAME AS SUBE

 from LG_217_ITEMS ITM

 LEFT JOIN LG_217_01_STLINE STL ON STL.STOCKREF=ITM.LOGICALREF
 LEFT JOIN LG_217_01_STFICHE STF ON STF.LOGICALREF=STL.STFICHEREF
 LEFT JOIN L_CAPIDIV D ON D.NR=STF.BRANCH AND D.FIRMNR=217

 WHERE STL.TRCODE=7


 use [TIGER2]
 go
 create nonclustered index IX1
 on [dbo].[LG_217_01_STLINE]([TRCODE])
 include([STOCKREF],[LINENET])
 go

 select * from VM_SATISLAR where BRAND='DR.OETKER'

 select BRAND,sum(LINENET) as TOTAL from VM_SATISLAR group by BRAND order by 2 desc

 sp_updatestats

  alter view VM_SATISLAR
	 as
	 select 

	 ITM.CODE MALZEMEKODU,ITM.NAME MALZEMEADI,ITM.KEYWORD1 AS MARKA,ITM.KEYWORD2 AS KATEGORI1,ITM.KEYWORD3 AS KATEGORI2,
	 STL.DATE_ TARIH,STL.AMOUNT MIKTAR,STL.PRICE FIYAT,STL.LINENET TUTAR,
	 STF.BRANCH SUBENO,D.NAME AS SUBEADI

	 from LG_217_ITEMS ITM

	 LEFT JOIN LG_217_01_STLINE STL ON STL.STOCKREF=ITM.LOGICALREF
	 LEFT JOIN LG_217_01_STFICHE STF ON STF.LOGICALREF=STL.STFICHEREF
	 LEFT JOIN L_CAPIDIV D ON D.NR=STF.BRANCH AND D.FIRMNR=217

	 WHERE STL.TRCODE=7
 
 select marka,sum(tutar) as TUTAR from VM_SATISLAR group by marka order by 2 desc

 select datepart(month,TARIH) as AY,sum(TUTAR) as TUTAR from VM_SATISLAR group by datepart(month,TARIH) order by 1

 select TOP 100 MALZEMEKODU,MALZEMEADI,sum(TUTAR) from VM_SATISLAR group by MALZEMEKODU,MALZEMEADI order by 3 desc