SELECT * FROM HR.EMPLOYEES

SELECT FIRST_NAME FROM HR.EMPLOYEES

SELECT FIRST_NAME, SALARY+1000 FROM HR.EMPLOYEES

SELECT FIRST_NAME, SALARY+1000 AS MAAS FROM HR.EMPLOYEES

SELECT FIRST_NAME, SALARY+1000 AS MAAS FROM HR.EMPLOYEES EMP

SELECT * FROM HR.EMPLOYEES WHERE JOB_ID = 'IT_PROG'

SELECT COUNT(1) FROM HR.EMPLOYEES

SELECT COUNT(*) FROM ALL_TAB_COLS WHERE TABLE_NAME = 'EMPLOYEES'

SELECT * FROM HR.EMPLOYEES WHERE JOB_ID = 'IT_PROG' ORDER BY FIRST_NAME

SELECT * FROM HR.EMPLOYEES WHERE JOB_ID = 'IT_PROG' ORDER BY FIRST_NAME DESC

SELECT FIRST_NAME, SALARY+1000 AS MAAS FROM HR.EMPLOYEES EMP

SELECT FIRST_NAME, SALARY/12 AS MAAS FROM HR.EMPLOYEES EMP

SELECT * FROM HR.EMPLOYEES WHERE JOB_ID IN ('IT_PROG', 'FI_ACCOUNT')

SELECT * FROM HR.EMPLOYEES WHERE JOB_ID NOT IN ('IT_PROG', 'FI_ACCOUNT')

SELECT * FROM HR.EMPLOYEES WHERE SALARY > 10000 AND SALARY < 20000

SELECT * FROM HR.EMPLOYEES WHERE SALARY BETWEEN 10000 AND 20000

SELECT * FROM HR.EMPLOYEES WHERE upper(FIRST_NAME) LIKE '%V%'

SELECT * FROM HR.EMPLOYEES WHERE lower(FIRST_NAME) LIKE '%v%'

SELECT * FROM HR.EMPLOYEES WHERE FIRST_NAME LIKE '%V%'

SELECT INITCAP(upper(FIRST_NAME)) AS "INIT", upper(FIRST_NAME) FROM HR.EMPLOYEES WHERE INITCAP(upper(FIRST_NAME)) LIKE '%v%' ORDER BY INIT

SELECT CONCAT(FIRST_NAME,LAST_NAME) FROM HR.EMPLOYEES

SELECT FIRST_NAME || ' '|| LAST_NAME FROM HR.EMPLOYEES

SELECT FIRST_NAME || ' '|| LAST_NAME as ISIM FROM HR.EMPLOYEES

SELECT EMPLOYEE_ID, LENGTH(LAST_NAME) FROM HR.EMPLOYEES

SELECT EMPLOYEE_ID, LAST_NAME, LENGTH(LAST_NAME), INSTR(LAST_NAME, 'a') FROM HR.EMPLOYEES

SELECT EMPLOYEE_ID, LAST_NAME, LENGTH(LAST_NAME), INSTR(LAST_NAME, 'a'), SUBSTR(JOB_ID,4), JOB_ID FROM HR.EMPLOYEES

explain plan for select * from hr.employees emp where emp.first_name like '%A%' or emp.first_name like '%a%'

SELECT * FROM table(DBMS_XPLAN.DISPLAY (FORMAT=>'ALL'))

SELECT * FROM HR.EMPLOYEES

SELECT EMAIL || '@' ||'[abc.com](http://abc.com/)' MAIL FROM HR.EMPLOYEES

SELECT EMAIL || '@' ||'[abc.com](http://abc.com/)' FROM HR.EMPLOYEES WHERE SUBSTR(JOB_ID,0,2) = 'IT'

SELECT EMAIL || '@' ||'[abc.com](http://abc.com/)' AS EMAIL FROM HR.EMPLOYEES WHERE SUBSTR(JOB_ID,0,2) = 'IT'

SELECT EMAIL || '@' || '[abc.com](http://abc.com/)' MAIL FROM HR.EMPLOYEES WHERE JOB_ID LIKE 'IT%'

SELECT EMPLOYEE_ID, LAST_NAME, LENGTH(LAST_NAME), INSTR(LAST_NAME, 'a'), SUBSTR(JOB_ID,6,2), JOB_ID FROM HR.EMPLOYEES

SELECT SUBSTR(EMAIL || '@' || '[abc.com](http://abc.com/)', 0, INSTR(EMAIL || '@' || '[abc.com](http://abc.com/)', '@')) || '[abcIT.com](http://abcit.com/)' FROM HR.EMPLOYEES WHERE SUBSTR(JOB_ID,0,2) = 'IT'

SELECT REPLACE(EMAIL || '@' || '[abc.com](http://abc.com/)', '[abc.com](http://abc.com/)', '[abcIT.com](http://abcit.com/)') FROM HR.EMPLOYEES WHERE SUBSTR(JOB_ID,0,2) = 'IT'

SELECT REPLACE(EMAIL || '@' || '[abc.com](http://abc.com/)', '[abc.com](http://abc.com/)', '[abcIT.com](http://abcit.com/)'), SUBSTR(EMAIL || '@' || '[abc.com](http://abc.com/)', 0, INSTR(EMAIL || '@' || '[abc.com](http://abc.com/)', '@')) || '[abcIT.com](http://abcit.com/)' FROM HR.EMPLOYEES WHERE SUBSTR(JOB_ID,0,2) = 'IT'

SELECT SALARY, LPAD(SALARY, 6,'0') FROM HR.EMPLOYEES

SELECT SALARY, RPAD(SALARY, 6,'0') FROM HR.EMPLOYEES

SELECT ROUND(SALARY/12), SALARY/12 FROM HR.EMPLOYEES

SELECT ROUND(SALARY/12,4), SALARY/12 FROM HR.EMPLOYEES

SELECT FLOOR(SALARY/12), SALARY/12 FROM HR.EMPLOYEES

SELECT * FROM DUAL

SELECT SYSDATE FROM DUAL

SELECT MOD(10,7) FROM DUAL

SELECT * FROM HR.EMPLOYEES WHERE HIRE_DATE BETWEEN ADD_MONTHS('01-JUN-05',-12) AND '01-JUN-05'

SELECT * FROM HR.EMPLOYEES

SELECT HIRE_DATE, LAST_DAY(HIRE_DATE) FROM HR.EMPLOYEES

SELECT TRUNC(HIRE_DATE, 'MM'),HIRE_DATE, LAST_DAY(HIRE_DATE) FROM HR.EMPLOYEES

SELECT TRUNC(HIRE_DATE, 'YYYY'), TRUNC(HIRE_DATE, 'MM'),HIRE_DATE, LAST_DAY(HIRE_DATE) FROM HR.EMPLOYEES

SELECT TO_CHAR(HIRE_DATE, 'DD.MM.YYYY') FROM HR.EMPLOYEES

SELECT SALARY, TO_CHAR(SALARY, '$99,999.00') FROM HR.EMPLOYEES

SELECT * FROM HR.EMPLOYEES WHERE HIRE_DATE < '01.01.2005' -- error

SELECT * FROM HR.EMPLOYEES WHERE HIRE_DATE < TO_DATE('01.01.2005','DD.MM.YYYY')

SELECT * FROM HR.EMPLOYEES WHERE HIRE_DATE < TO_DATE('01.01.2005','DD.MM.YYYY') ORDER BY HIRE_DATE DESC

SELECT * FROM HR.EMPLOYEES

SELECT NVL(COMMISSION_PCT, 0) FROM HR.EMPLOYEES

SELECT SALARY*NVL(COMMISSION_PCT, 0), SALARY+(SALARY*COMMISSION_PCT) FROM HR.EMPLOYEES

SELECT SALARY+(SALARY*NVL(COMMISSION_PCT, 0)), SALARY+(SALARY*COMMISSION_PCT) FROM HR.EMPLOYEES

SELECT FIRST_NAME,COMMISSION_PCT, NVL2(COMMISSION_PCT,'KOMISYON VAR','KOMISYON YOK') FROM HR.EMPLOYEES

SELECT LAST_NAME, JOB_ID, SALARY, CASE WHEN JOB_ID = 'IT_PROG' THEN SALARY*1.05 ELSE SALARY END NEW_SALARY FROM HR.EMPLOYEES

SELECT LAST_NAME, JOB_ID, SALARY, CASE WHEN COMMISSION_PCT IS NOT NULL THEN TO_CHAR(COMMISSION_PCT) ELSE 'KOMISYON YOK' END NEW_SALARY FROM HR.EMPLOYEES

SELECT FIRST_NAME,COMMISSION_PCT, NVL2(COMMISSION_PCT, TO_CHAR(COMMISSION_PCT),'KOMISYON YOK') FROM HR.EMPLOYEES

SELECT LAST_NAME, JOB_ID, SALARY, CASE JOB_ID WHEN 'IT_PROG' THEN SALARY*1.05 WHEN 'AD_PRES' THEN SALARY*1.01 ELSE SALARY END NEW_SALARY FROM HR.EMPLOYEES

SELECT AVG(SALARY), MAX(SALARY), MIN(SALARY), SUM(SALARY) FROM HR.EMPLOYEES

SELECT JOB_ID, AVG(SALARY), MAX(SALARY), MIN(SALARY), SUM(SALARY) FROM HR.EMPLOYEES GROUP BY JOB_ID

SELECT JOB_ID, AVG(SALARY), MAX(SALARY), MIN(SALARY), SUM(SALARY) FROM HR.EMPLOYEES GROUP BY JOB_ID ORDER BY AVG(SALARY)



