/*
TRUNCATE TABLE PAYMENT
TRUNCATE TABLE ORDERDETAIL
TRUNCATE TABLE ORDER_
TRUNCATE TABLE BASKETDETAIL
TRUNCATE TABLE BASKET
*/
BEGIN TRAN

DECLARE @BASKETID AS INT
INSERT INTO BASKET (USERID,STATUS_,CREATEDATE) VALUES (1,0,GETDATE())
SET @BASKETID=@@IDENTITY

IF @@ERROR>0
BEGIN
	ROLLBACK TRAN
	RETURN 
END
 

INSERT INTO BASKETDETAIL (BASKETID,ITEMCODE,AMOUNT,PRICE,DATE_) VALUES (@BASKETID,'MALZEME1',1,400,GETDATE())
INSERT INTO BASKETDETAIL (BASKETID,ITEMCODE,AMOUNT,PRICE,DATE_) VALUES (@BASKETID,'MALZEME3',3,100,GETDATE())

IF @@ERROR>0
BEGIN
	ROLLBACK TRAN
	RETURN 
END

DECLARE @ORDERID AS INT
INSERT INTO ORDER_ (BASKETID,DATE_,STATUS_)
VALUES (@BASKETID,GETDATE(),1)
SET @ORDERID= @@IDENTITY

IF @@ERROR>0
BEGIN
	ROLLBACK TRAN
	RETURN 
END

INSERT INTO ORDERDETAIL (ORDERID,ITEMCODE,AMOUNT,PRICE,DATE_)


SELECT @ORDERID,ITEMCODE,AMOUNT,PRICE,GETDATE() FROM BASKETDETAIL WHERE BASKETID IN
(SELECT BASKETID FROM ORDER_ WHERE ID=@BASKETID)

UPDATE BASKET SET STATUS_=1 WHERE ID=@BASKETID
IF @@ERROR>0
BEGIN
	ROLLBACK TRAN
	RETURN 
END

INSERT INTO PAYMENT (ORDERID,PAYMENTAMOUNT,PAYMENTTYPE,STATUS_,APPROVECODE,DATE_)
VALUES (@ORDERID,700,0,1,'APPR8988234234234234234',GETDATE())
IF @@ERROR>0
BEGIN
	ROLLBACK TRAN
	RETURN 
END

UPDATE ORDER_ SET STATUS_=2 WHERE ID=@ORDERID

UPDATE BASKET SET STATUS_=2 WHERE ID=@BASKETID
 
IF @@ERROR>0
BEGIN
	ROLLBACK TRAN
	RETURN 
END
COMMIT


 SELECT * FROM BASKET
 --SELECT * FROM BASKETDETAIL

SELECT * FROM ORDER_
---SELECT * FROM ORDERDETAIL
SELECT * FROM PAYMENT



 