
CREATE TABLE [dbo].[LG_217_ITEMS](
	[LOGICALREF] [int] NOT NULL,
	[ACTIVE] [smallint] NULL,
	[CARDTYPE] [smallint] NULL,
	[CODE] [varchar](25) NULL,
	[NAME] [varchar](51) NULL,
	[STGRPCODE] [varchar](25) NULL,
	[PRODUCERCODE] [varchar](101) NULL,
	[SPECODE] [varchar](11) NULL,
	[CYPHCODE] [varchar](11) NULL,
	[CLASSTYPE] [smallint] NULL,
	[PURCHBRWS] [smallint] NULL,
	[SALESBRWS] [smallint] NULL,
	[MTRLBRWS] [smallint] NULL,
	[VAT] [float] NULL,
	[PAYMENTREF] [int] NULL,
	[TRACKTYPE] [smallint] NULL,
	[LOCTRACKING] [smallint] NULL,
	[TOOL] [smallint] NULL,
	[AUTOINCSL] [smallint] NULL,
	[DIVLOTSIZE] [smallint] NULL,
	[SHELFLIFE] [float] NULL,
	[SHELFDATE] [smallint] NULL,
	[DOMINANTREFS1] [int] NULL,
	[DOMINANTREFS2] [int] NULL,
	[DOMINANTREFS3] [int] NULL,
	[DOMINANTREFS4] [int] NULL,
	[DOMINANTREFS5] [int] NULL,
	[DOMINANTREFS6] [int] NULL,
	[DOMINANTREFS7] [int] NULL,
	[DOMINANTREFS8] [int] NULL,
	[DOMINANTREFS9] [int] NULL,
	[DOMINANTREFS10] [int] NULL,
	[DOMINANTREFS11] [int] NULL,
	[DOMINANTREFS12] [int] NULL,
	[IMAGEINC] [smallint] NULL,
	[TEXTINC] [smallint] NULL,
	[DEPRTYPE] [smallint] NULL,
	[DEPRRATE] [float] NULL,
	[DEPRDUR] [smallint] NULL,
	[SALVAGEVAL] [float] NULL,
	[REVALFLAG] [smallint] NULL,
	[REVDEPRFLAG] [smallint] NULL,
	[PARTDEP] [smallint] NULL,
	[DEPRTYPE2] [smallint] NULL,
	[DEPRRATE2] [float] NULL,
	[DEPRDUR2] [smallint] NULL,
	[REVALFLAG2] [smallint] NULL,
	[REVDEPRFLAG2] [smallint] NULL,
	[PARTDEP2] [smallint] NULL,
	[APPROVED] [smallint] NULL,
	[UNITSETREF] [int] NULL,
	[QCCSETREF] [int] NULL,
	[DISTAMOUNT] [float] NULL,
	[CAPIBLOCK_CREATEDBY] [smallint] NULL,
	[CAPIBLOCK_CREADEDDATE] [datetime] NULL,
	[CAPIBLOCK_CREATEDHOUR] [smallint] NULL,
	[CAPIBLOCK_CREATEDMIN] [smallint] NULL,
	[CAPIBLOCK_CREATEDSEC] [smallint] NULL,
	[CAPIBLOCK_MODIFIEDBY] [smallint] NULL,
	[CAPIBLOCK_MODIFIEDDATE] [datetime] NULL,
	[CAPIBLOCK_MODIFIEDHOUR] [smallint] NULL,
	[CAPIBLOCK_MODIFIEDMIN] [smallint] NULL,
	[CAPIBLOCK_MODIFIEDSEC] [smallint] NULL,
	[SITEID] [smallint] NULL,
	[RECSTATUS] [smallint] NULL,
	[ORGLOGICREF] [int] NULL,
	[UNIVID] [varchar](25) NULL,
	[DISTLOTUNITS] [smallint] NULL,
	[COMBLOTUNITS] [smallint] NULL,
	[WFSTATUS] [int] NULL,
	[DISTPOINT] [float] NULL,
	[CAMPPOINT] [float] NULL,
	[CANUSEINTRNS] [smallint] NULL,
	[ISONR] [varchar](11) NULL,
	[GROUPNR] [varchar](9) NULL,
	[PRODCOUNTRY] [varchar](13) NULL,
	[ADDTAXREF] [int] NULL,
	[QPRODAMNT] [float] NULL,
	[QPRODUOM] [int] NULL,
	[QPRODSRCINDEX] [smallint] NULL,
	[EXTACCESSFLAGS] [int] NULL,
	[PACKET] [smallint] NULL,
	[SALVAGEVAL2] [float] NULL,
	[SELLVAT] [float] NULL,
	[RETURNVAT] [float] NULL,
	[LOGOID] [varchar](25) NULL,
	[LIDCONFIRMED] [smallint] NULL,
	[GTIPCODE] [varchar](25) NULL,
	[EXPCTGNO] [varchar](25) NULL,
	[B2CCODE] [varchar](25) NULL,
	[MARKREF] [int] NULL,
	[IMAGE2INC] [smallint] NULL,
	[AVRWHDURATION] [float] NULL,
	[EXTCARDFLAGS] [int] NULL,
	[MINORDAMOUNT] [float] NULL,
	[FREIGHTPLACE] [varchar](51) NULL,
	[FREIGHTTYPCODE1] [varchar](13) NULL,
	[FREIGHTTYPCODE2] [varchar](13) NULL,
	[FREIGHTTYPCODE3] [varchar](13) NULL,
	[FREIGHTTYPCODE4] [varchar](13) NULL,
	[FREIGHTTYPCODE5] [varchar](13) NULL,
	[FREIGHTTYPCODE6] [varchar](13) NULL,
	[FREIGHTTYPCODE7] [varchar](13) NULL,
	[FREIGHTTYPCODE8] [varchar](13) NULL,
	[FREIGHTTYPCODE9] [varchar](13) NULL,
	[FREIGHTTYPCODE10] [varchar](13) NULL,
	[STATECODE] [varchar](13) NULL,
	[STATENAME] [varchar](41) NULL,
	[EXPCATEGORY] [varchar](25) NULL,
	[LOSTFACTOR] [float] NULL,
	[TEXTINCENG] [smallint] NULL,
	[EANBARCODE] [varchar](25) NULL,
	[DEPRCLASSTYPE] [varchar](31) NULL,
	[WFLOWCRDREF] [int] NULL,
	[SELLPRVAT] [float] NULL,
	[RETURNPRVAT] [float] NULL,
	[LOWLEVELCODES1] [int] NULL,
	[LOWLEVELCODES2] [int] NULL,
	[LOWLEVELCODES3] [int] NULL,
	[LOWLEVELCODES4] [int] NULL,
	[LOWLEVELCODES5] [int] NULL,
	[LOWLEVELCODES6] [int] NULL,
	[LOWLEVELCODES7] [int] NULL,
	[LOWLEVELCODES8] [int] NULL,
	[LOWLEVELCODES9] [int] NULL,
	[LOWLEVELCODES10] [int] NULL,
	[ORGLOGOID] [varchar](25) NULL,
	[QPRODDEPART] [smallint] NULL,
	[CANCONFIGURE] [smallint] NULL,
	[CHARSETREF] [int] NULL,
	[CANDEDUCT] [smallint] NULL,
	[CONSCODEREF] [int] NULL,
	[SPECODE2] [varchar](11) NULL,
	[SPECODE3] [varchar](11) NULL,
	[SPECODE4] [varchar](11) NULL,
	[SPECODE5] [varchar](11) NULL,
	[EXPENSE] [smallint] NULL,
	[ORIGIN] [varchar](25) NULL,
	[NAME2] [varchar](51) NULL,
	[COMPKDVUSE] [smallint] NULL,
	[USEDINPERIODS] [smallint] NULL,
	[EXIMTAX1] [float] NULL,
	[EXIMTAX2] [float] NULL,
	[EXIMTAX3] [float] NULL,
	[EXIMTAX4] [float] NULL,
	[EXIMTAX5] [float] NULL,
	[PRODUCTLEVEL] [smallint] NULL,
	[APPSPEVATMATRAH] [smallint] NULL,
	[NAME3] [varchar](201) NULL,
	[FACOSTKEYS] [smallint] NULL,
	[KKLINESDISABLE] [smallint] NULL,
	[APPROVE] [smallint] NULL,
	[APPROVEDATE] [datetime] NULL,
	[GLOBALID] [varchar](51) NULL,
	[SALEDEDUCTPART1] [smallint] NULL,
	[SALEDEDUCTPART2] [smallint] NULL,
	[PURCDEDUCTPART1] [smallint] NULL,
	[PURCDEDUCTPART2] [smallint] NULL,
	[CATEGORYID] [varchar](51) NULL,
	[CATEGORYNAME] [varchar](256) NULL,
	[KEYWORD1] [varchar](121) NULL,
	[KEYWORD2] [varchar](121) NULL,
	[KEYWORD3] [varchar](121) NULL,
	[KEYWORD4] [varchar](121) NULL,
	[KEYWORD5] [varchar](121) NULL,
	[GUID] [varchar](37) NULL,
	[DEMANDMEETSORTFLD1] [varchar](51) NULL,
	[DEMANDMEETSORTFLD2] [varchar](51) NULL,
	[DEMANDMEETSORTFLD3] [varchar](51) NULL,
	[DEMANDMEETSORTFLD4] [varchar](51) NULL,
	[DEMANDMEETSORTFLD5] [varchar](51) NULL,
	[DEDUCTCODE] [varchar](11) NULL,
	[PROJECTREF] [int] NULL,
	[NAME4] [varchar](201) NULL,
	[QPRODSUBAMNT] [float] NULL,
	[QPRODSUBUOM] [int] NULL,
	[QPRODSUBSRCINDEX] [smallint] NULL,
	[QPRODSUBDEPART] [smallint] NULL,
	LOG_HOSTNAME VARCHAR(255),
	LOG_DATE DATETIME,
	LOG_PROGRAM VARCHAR(255),
	LOG_USERNAME VARCHAR(255),
	LOG_SQL VARCHAR(MAX),
	ACTION_TYPE VARCHAR(10),
)

alter TRIGGER ITEMS_LOG_UPDATE ON LG_217_ITEMS
AFTER UPDATE
AS
BEGIN

declare	@LOG_HOSTNAME as varchar(255)=HOST_NAME()
declare @LOG_DATE as datetime
set @LOG_DATE=GETDATE()
declare @LOG_PROGRAM as varchar(255)=PROGRAM_NAME()
declare @LOG_USERNAME as varchar(255)=SUSER_NAME()
declare @LOG_SQL as varchar(MAX)
declare @LOG_ACTIONTYPE as varchar(10)='UPDATE'

select GETDATE()
DBCC INPUTBUFFER(@@SPID)


create table #T(EVENTTYPE varchar(100),PARAMETERS_ varchar(100),EVENTINFO varchar(max))
declare @SQL as nvarchar(max)
set @SQL='insert into #T exec ('' DBCC INPUTBUFFER('+CONVERT(VARCHAR,@@SPID)+')'')'
exec SP_EXECUTESQL @SQL

select @LOG_SQL=EVENTINFO from #T

drop table #T

insert into LOGDB.dbo.LG_217_ITEMS		
(LOGICALREF, ACTIVE, CARDTYPE, CODE, NAME, STGRPCODE, PRODUCERCODE, SPECODE, CYPHCODE, CLASSTYPE, PURCHBRWS, SALESBRWS, MTRLBRWS, VAT, PAYMENTREF, TRACKTYPE, LOCTRACKING, TOOL, AUTOINCSL, DIVLOTSIZE, SHELFLIFE, SHELFDATE, DOMINANTREFS1, DOMINANTREFS2, DOMINANTREFS3, DOMINANTREFS4, DOMINANTREFS5, DOMINANTREFS6, DOMINANTREFS7, DOMINANTREFS8, DOMINANTREFS9, DOMINANTREFS10, DOMINANTREFS11, DOMINANTREFS12, IMAGEINC, TEXTINC, DEPRTYPE, DEPRRATE, DEPRDUR, SALVAGEVAL, REVALFLAG, REVDEPRFLAG, PARTDEP, DEPRTYPE2, DEPRRATE2, DEPRDUR2, REVALFLAG2, REVDEPRFLAG2, PARTDEP2, APPROVED, UNITSETREF, QCCSETREF, DISTAMOUNT, CAPIBLOCK_CREATEDBY, CAPIBLOCK_CREADEDDATE, CAPIBLOCK_CREATEDHOUR, CAPIBLOCK_CREATEDMIN, CAPIBLOCK_CREATEDSEC, CAPIBLOCK_MODIFIEDBY, CAPIBLOCK_MODIFIEDDATE, CAPIBLOCK_MODIFIEDHOUR, CAPIBLOCK_MODIFIEDMIN, CAPIBLOCK_MODIFIEDSEC, SITEID, RECSTATUS, ORGLOGICREF, UNIVID, DISTLOTUNITS, COMBLOTUNITS, WFSTATUS, DISTPOINT, CAMPPOINT, CANUSEINTRNS, ISONR, GROUPNR, PRODCOUNTRY, ADDTAXREF, QPRODAMNT, QPRODUOM, QPRODSRCINDEX, EXTACCESSFLAGS, PACKET, SALVAGEVAL2, SELLVAT, RETURNVAT, LOGOID, LIDCONFIRMED, GTIPCODE, EXPCTGNO, B2CCODE, MARKREF, IMAGE2INC, AVRWHDURATION, EXTCARDFLAGS, MINORDAMOUNT, FREIGHTPLACE, FREIGHTTYPCODE1, FREIGHTTYPCODE2, FREIGHTTYPCODE3, FREIGHTTYPCODE4, FREIGHTTYPCODE5, FREIGHTTYPCODE6, FREIGHTTYPCODE7, FREIGHTTYPCODE8, FREIGHTTYPCODE9, FREIGHTTYPCODE10, STATECODE, STATENAME, EXPCATEGORY, LOSTFACTOR, TEXTINCENG, EANBARCODE, DEPRCLASSTYPE, WFLOWCRDREF, SELLPRVAT, RETURNPRVAT, LOWLEVELCODES1, LOWLEVELCODES2, LOWLEVELCODES3, LOWLEVELCODES4, LOWLEVELCODES5, LOWLEVELCODES6, LOWLEVELCODES7, LOWLEVELCODES8, LOWLEVELCODES9, LOWLEVELCODES10, ORGLOGOID, QPRODDEPART, CANCONFIGURE, CHARSETREF, CANDEDUCT, CONSCODEREF, SPECODE2, SPECODE3, SPECODE4, SPECODE5, EXPENSE, ORIGIN, NAME2, COMPKDVUSE, USEDINPERIODS, EXIMTAX1, EXIMTAX2, EXIMTAX3, EXIMTAX4, EXIMTAX5, PRODUCTLEVEL, APPSPEVATMATRAH, NAME3, FACOSTKEYS, KKLINESDISABLE, APPROVE, APPROVEDATE, GLOBALID, SALEDEDUCTPART1, SALEDEDUCTPART2, PURCDEDUCTPART1, PURCDEDUCTPART2, CATEGORYID, CATEGORYNAME, KEYWORD1, KEYWORD2, KEYWORD3, KEYWORD4, KEYWORD5, GUID, DEMANDMEETSORTFLD1, DEMANDMEETSORTFLD2, DEMANDMEETSORTFLD3, DEMANDMEETSORTFLD4, DEMANDMEETSORTFLD5, DEDUCTCODE, PROJECTREF, NAME4, QPRODSUBAMNT, QPRODSUBUOM, QPRODSUBSRCINDEX, QPRODSUBDEPART , LOG_HOSTNAME, LOG_DATE, LOG_PROGRAM, LOG_USERNAME, LOG_SQL, ACTION_TYPE)
select 
LOGICALREF, ACTIVE, CARDTYPE, CODE, NAME, STGRPCODE, PRODUCERCODE, SPECODE, CYPHCODE, CLASSTYPE, PURCHBRWS, SALESBRWS, MTRLBRWS, VAT, PAYMENTREF, TRACKTYPE, LOCTRACKING, TOOL, AUTOINCSL, DIVLOTSIZE, SHELFLIFE, SHELFDATE, DOMINANTREFS1, DOMINANTREFS2, DOMINANTREFS3, DOMINANTREFS4, DOMINANTREFS5, DOMINANTREFS6, DOMINANTREFS7, DOMINANTREFS8, DOMINANTREFS9, DOMINANTREFS10, DOMINANTREFS11, DOMINANTREFS12, IMAGEINC, TEXTINC, DEPRTYPE, DEPRRATE, DEPRDUR, SALVAGEVAL, REVALFLAG, REVDEPRFLAG, PARTDEP, DEPRTYPE2, DEPRRATE2, DEPRDUR2, REVALFLAG2, REVDEPRFLAG2, PARTDEP2, APPROVED, UNITSETREF, QCCSETREF, DISTAMOUNT, CAPIBLOCK_CREATEDBY, CAPIBLOCK_CREADEDDATE, CAPIBLOCK_CREATEDHOUR, CAPIBLOCK_CREATEDMIN, CAPIBLOCK_CREATEDSEC, CAPIBLOCK_MODIFIEDBY, CAPIBLOCK_MODIFIEDDATE, CAPIBLOCK_MODIFIEDHOUR, CAPIBLOCK_MODIFIEDMIN, CAPIBLOCK_MODIFIEDSEC, SITEID, RECSTATUS, ORGLOGICREF, UNIVID, DISTLOTUNITS, COMBLOTUNITS, WFSTATUS, DISTPOINT, CAMPPOINT, CANUSEINTRNS, ISONR, GROUPNR, PRODCOUNTRY, ADDTAXREF, QPRODAMNT, QPRODUOM, QPRODSRCINDEX, EXTACCESSFLAGS, PACKET, SALVAGEVAL2, SELLVAT, RETURNVAT, LOGOID, LIDCONFIRMED, GTIPCODE, EXPCTGNO, B2CCODE, MARKREF, IMAGE2INC, AVRWHDURATION, EXTCARDFLAGS, MINORDAMOUNT, FREIGHTPLACE, FREIGHTTYPCODE1, FREIGHTTYPCODE2, FREIGHTTYPCODE3, FREIGHTTYPCODE4, FREIGHTTYPCODE5, FREIGHTTYPCODE6, FREIGHTTYPCODE7, FREIGHTTYPCODE8, FREIGHTTYPCODE9, FREIGHTTYPCODE10, STATECODE, STATENAME, EXPCATEGORY, LOSTFACTOR, TEXTINCENG, EANBARCODE, DEPRCLASSTYPE, WFLOWCRDREF, SELLPRVAT, RETURNPRVAT, LOWLEVELCODES1, LOWLEVELCODES2, LOWLEVELCODES3, LOWLEVELCODES4, LOWLEVELCODES5, LOWLEVELCODES6, LOWLEVELCODES7, LOWLEVELCODES8, LOWLEVELCODES9, LOWLEVELCODES10, ORGLOGOID, QPRODDEPART, CANCONFIGURE, CHARSETREF, CANDEDUCT, CONSCODEREF, SPECODE2, SPECODE3, SPECODE4, SPECODE5, EXPENSE, ORIGIN, NAME2, COMPKDVUSE, USEDINPERIODS, EXIMTAX1, EXIMTAX2, EXIMTAX3, EXIMTAX4, EXIMTAX5, PRODUCTLEVEL, APPSPEVATMATRAH, NAME3, FACOSTKEYS, KKLINESDISABLE, APPROVE, APPROVEDATE, GLOBALID, SALEDEDUCTPART1, SALEDEDUCTPART2, PURCDEDUCTPART1, PURCDEDUCTPART2, CATEGORYID, CATEGORYNAME, KEYWORD1, KEYWORD2, KEYWORD3, KEYWORD4, KEYWORD5, GUID, DEMANDMEETSORTFLD1, DEMANDMEETSORTFLD2, DEMANDMEETSORTFLD3, DEMANDMEETSORTFLD4, DEMANDMEETSORTFLD5, DEDUCTCODE, PROJECTREF, NAME4, QPRODSUBAMNT, QPRODSUBUOM, QPRODSUBSRCINDEX, QPRODSUBDEPART , @LOG_HOSTNAME, @LOG_DATE, @LOG_PROGRAM, @LOG_USERNAME, @LOG_SQL, @LOG_ACTIONTYPE
from deleted
end

select * from LG_217_ITEMS
select * from TIGER2.dbo.LG_217_ITEMS where LOGICALREF='84'

update TIGER2.DBO.LG_217_ITEMS set NAME=NAME+'deneme' where LOGICALREF=84

truncate table LG_217_ITEMS

select * from TIGER2.dbo.LG_217_ITEMS

drop database TIGER2



alter TRIGGER ITEMS_LOG_DELETE ON LG_217_ITEMS
AFTER DELETE
AS
BEGIN

declare	@LOG_HOSTNAME as varchar(255)=HOST_NAME()
declare @LOG_DATE as datetime
set @LOG_DATE=GETDATE()
declare @LOG_PROGRAM as varchar(255)=PROGRAM_NAME()
declare @LOG_USERNAME as varchar(255)=SUSER_NAME()
declare @LOG_SQL as varchar(MAX)
declare @LOG_ACTIONTYPE as varchar(10)='DELETE'

select GETDATE()
DBCC INPUTBUFFER(@@SPID)


create table #T(EVENTTYPE varchar(100),PARAMETERS_ varchar(100),EVENTINFO varchar(max))
declare @SQL as nvarchar(max)
set @SQL='insert into #T exec ('' DBCC INPUTBUFFER('+CONVERT(VARCHAR,@@SPID)+')'')'
exec SP_EXECUTESQL @SQL

select @LOG_SQL=EVENTINFO from #T

drop table #T

insert into LOGDB.dbo.LG_217_ITEMS		
(LOGICALREF, ACTIVE, CARDTYPE, CODE, NAME, STGRPCODE, PRODUCERCODE, SPECODE, CYPHCODE, CLASSTYPE, PURCHBRWS, SALESBRWS, MTRLBRWS, VAT, PAYMENTREF, TRACKTYPE, LOCTRACKING, TOOL, AUTOINCSL, DIVLOTSIZE, SHELFLIFE, SHELFDATE, DOMINANTREFS1, DOMINANTREFS2, DOMINANTREFS3, DOMINANTREFS4, DOMINANTREFS5, DOMINANTREFS6, DOMINANTREFS7, DOMINANTREFS8, DOMINANTREFS9, DOMINANTREFS10, DOMINANTREFS11, DOMINANTREFS12, IMAGEINC, TEXTINC, DEPRTYPE, DEPRRATE, DEPRDUR, SALVAGEVAL, REVALFLAG, REVDEPRFLAG, PARTDEP, DEPRTYPE2, DEPRRATE2, DEPRDUR2, REVALFLAG2, REVDEPRFLAG2, PARTDEP2, APPROVED, UNITSETREF, QCCSETREF, DISTAMOUNT, CAPIBLOCK_CREATEDBY, CAPIBLOCK_CREADEDDATE, CAPIBLOCK_CREATEDHOUR, CAPIBLOCK_CREATEDMIN, CAPIBLOCK_CREATEDSEC, CAPIBLOCK_MODIFIEDBY, CAPIBLOCK_MODIFIEDDATE, CAPIBLOCK_MODIFIEDHOUR, CAPIBLOCK_MODIFIEDMIN, CAPIBLOCK_MODIFIEDSEC, SITEID, RECSTATUS, ORGLOGICREF, UNIVID, DISTLOTUNITS, COMBLOTUNITS, WFSTATUS, DISTPOINT, CAMPPOINT, CANUSEINTRNS, ISONR, GROUPNR, PRODCOUNTRY, ADDTAXREF, QPRODAMNT, QPRODUOM, QPRODSRCINDEX, EXTACCESSFLAGS, PACKET, SALVAGEVAL2, SELLVAT, RETURNVAT, LOGOID, LIDCONFIRMED, GTIPCODE, EXPCTGNO, B2CCODE, MARKREF, IMAGE2INC, AVRWHDURATION, EXTCARDFLAGS, MINORDAMOUNT, FREIGHTPLACE, FREIGHTTYPCODE1, FREIGHTTYPCODE2, FREIGHTTYPCODE3, FREIGHTTYPCODE4, FREIGHTTYPCODE5, FREIGHTTYPCODE6, FREIGHTTYPCODE7, FREIGHTTYPCODE8, FREIGHTTYPCODE9, FREIGHTTYPCODE10, STATECODE, STATENAME, EXPCATEGORY, LOSTFACTOR, TEXTINCENG, EANBARCODE, DEPRCLASSTYPE, WFLOWCRDREF, SELLPRVAT, RETURNPRVAT, LOWLEVELCODES1, LOWLEVELCODES2, LOWLEVELCODES3, LOWLEVELCODES4, LOWLEVELCODES5, LOWLEVELCODES6, LOWLEVELCODES7, LOWLEVELCODES8, LOWLEVELCODES9, LOWLEVELCODES10, ORGLOGOID, QPRODDEPART, CANCONFIGURE, CHARSETREF, CANDEDUCT, CONSCODEREF, SPECODE2, SPECODE3, SPECODE4, SPECODE5, EXPENSE, ORIGIN, NAME2, COMPKDVUSE, USEDINPERIODS, EXIMTAX1, EXIMTAX2, EXIMTAX3, EXIMTAX4, EXIMTAX5, PRODUCTLEVEL, APPSPEVATMATRAH, NAME3, FACOSTKEYS, KKLINESDISABLE, APPROVE, APPROVEDATE, GLOBALID, SALEDEDUCTPART1, SALEDEDUCTPART2, PURCDEDUCTPART1, PURCDEDUCTPART2, CATEGORYID, CATEGORYNAME, KEYWORD1, KEYWORD2, KEYWORD3, KEYWORD4, KEYWORD5, GUID, DEMANDMEETSORTFLD1, DEMANDMEETSORTFLD2, DEMANDMEETSORTFLD3, DEMANDMEETSORTFLD4, DEMANDMEETSORTFLD5, DEDUCTCODE, PROJECTREF, NAME4, QPRODSUBAMNT, QPRODSUBUOM, QPRODSUBSRCINDEX, QPRODSUBDEPART , LOG_HOSTNAME, LOG_DATE, LOG_PROGRAM, LOG_USERNAME, LOG_SQL, ACTION_TYPE)
select 
LOGICALREF, ACTIVE, CARDTYPE, CODE, NAME, STGRPCODE, PRODUCERCODE, SPECODE, CYPHCODE, CLASSTYPE, PURCHBRWS, SALESBRWS, MTRLBRWS, VAT, PAYMENTREF, TRACKTYPE, LOCTRACKING, TOOL, AUTOINCSL, DIVLOTSIZE, SHELFLIFE, SHELFDATE, DOMINANTREFS1, DOMINANTREFS2, DOMINANTREFS3, DOMINANTREFS4, DOMINANTREFS5, DOMINANTREFS6, DOMINANTREFS7, DOMINANTREFS8, DOMINANTREFS9, DOMINANTREFS10, DOMINANTREFS11, DOMINANTREFS12, IMAGEINC, TEXTINC, DEPRTYPE, DEPRRATE, DEPRDUR, SALVAGEVAL, REVALFLAG, REVDEPRFLAG, PARTDEP, DEPRTYPE2, DEPRRATE2, DEPRDUR2, REVALFLAG2, REVDEPRFLAG2, PARTDEP2, APPROVED, UNITSETREF, QCCSETREF, DISTAMOUNT, CAPIBLOCK_CREATEDBY, CAPIBLOCK_CREADEDDATE, CAPIBLOCK_CREATEDHOUR, CAPIBLOCK_CREATEDMIN, CAPIBLOCK_CREATEDSEC, CAPIBLOCK_MODIFIEDBY, CAPIBLOCK_MODIFIEDDATE, CAPIBLOCK_MODIFIEDHOUR, CAPIBLOCK_MODIFIEDMIN, CAPIBLOCK_MODIFIEDSEC, SITEID, RECSTATUS, ORGLOGICREF, UNIVID, DISTLOTUNITS, COMBLOTUNITS, WFSTATUS, DISTPOINT, CAMPPOINT, CANUSEINTRNS, ISONR, GROUPNR, PRODCOUNTRY, ADDTAXREF, QPRODAMNT, QPRODUOM, QPRODSRCINDEX, EXTACCESSFLAGS, PACKET, SALVAGEVAL2, SELLVAT, RETURNVAT, LOGOID, LIDCONFIRMED, GTIPCODE, EXPCTGNO, B2CCODE, MARKREF, IMAGE2INC, AVRWHDURATION, EXTCARDFLAGS, MINORDAMOUNT, FREIGHTPLACE, FREIGHTTYPCODE1, FREIGHTTYPCODE2, FREIGHTTYPCODE3, FREIGHTTYPCODE4, FREIGHTTYPCODE5, FREIGHTTYPCODE6, FREIGHTTYPCODE7, FREIGHTTYPCODE8, FREIGHTTYPCODE9, FREIGHTTYPCODE10, STATECODE, STATENAME, EXPCATEGORY, LOSTFACTOR, TEXTINCENG, EANBARCODE, DEPRCLASSTYPE, WFLOWCRDREF, SELLPRVAT, RETURNPRVAT, LOWLEVELCODES1, LOWLEVELCODES2, LOWLEVELCODES3, LOWLEVELCODES4, LOWLEVELCODES5, LOWLEVELCODES6, LOWLEVELCODES7, LOWLEVELCODES8, LOWLEVELCODES9, LOWLEVELCODES10, ORGLOGOID, QPRODDEPART, CANCONFIGURE, CHARSETREF, CANDEDUCT, CONSCODEREF, SPECODE2, SPECODE3, SPECODE4, SPECODE5, EXPENSE, ORIGIN, NAME2, COMPKDVUSE, USEDINPERIODS, EXIMTAX1, EXIMTAX2, EXIMTAX3, EXIMTAX4, EXIMTAX5, PRODUCTLEVEL, APPSPEVATMATRAH, NAME3, FACOSTKEYS, KKLINESDISABLE, APPROVE, APPROVEDATE, GLOBALID, SALEDEDUCTPART1, SALEDEDUCTPART2, PURCDEDUCTPART1, PURCDEDUCTPART2, CATEGORYID, CATEGORYNAME, KEYWORD1, KEYWORD2, KEYWORD3, KEYWORD4, KEYWORD5, GUID, DEMANDMEETSORTFLD1, DEMANDMEETSORTFLD2, DEMANDMEETSORTFLD3, DEMANDMEETSORTFLD4, DEMANDMEETSORTFLD5, DEDUCTCODE, PROJECTREF, NAME4, QPRODSUBAMNT, QPRODSUBUOM, QPRODSUBSRCINDEX, QPRODSUBDEPART , @LOG_HOSTNAME, @LOG_DATE, @LOG_PROGRAM, @LOG_USERNAME, @LOG_SQL, @LOG_ACTIONTYPE
from deleted
end

delete from TIGER2.DBO.LG_217_ITEMS where CODE='24670'

select * from LG_217_ITEMS
select * from TIGER2.dbo.LG_217_ITEMS where LOGICALREF='24670'

alter TRIGGER ITEMS_LOG ON LG_217_ITEMS
AFTER UPDATE,DELETE
AS
BEGIN

declare	@LOG_HOSTNAME as varchar(255)=HOST_NAME()
declare @LOG_DATE as datetime
set @LOG_DATE=GETDATE()
declare @LOG_PROGRAM as varchar(255)=PROGRAM_NAME()
declare @LOG_USERNAME as varchar(255)=SUSER_NAME()
declare @LOG_SQL as varchar(MAX)
declare @LOG_ACTIONTYPE as varchar(10)=''

if exists (select * from deleted)
	set @LOG_ACTIONTYPE='DELETE'
if exists (select * from INSERTED)
	set @LOG_ACTIONTYPE='UPDATE'

select GETDATE()
DBCC INPUTBUFFER(@@SPID)


create table #T(EVENTTYPE varchar(100),PARAMETERS_ varchar(100),EVENTINFO varchar(max))
declare @SQL as nvarchar(max)
set @SQL='insert into #T exec ('' DBCC INPUTBUFFER('+CONVERT(VARCHAR,@@SPID)+')'')'
exec SP_EXECUTESQL @SQL

select @LOG_SQL=EVENTINFO from #T

drop table #T

insert into LOGDB.dbo.LG_217_ITEMS		
(LOGICALREF, ACTIVE, CARDTYPE, CODE, NAME, STGRPCODE, PRODUCERCODE, SPECODE, CYPHCODE, CLASSTYPE, PURCHBRWS, SALESBRWS, MTRLBRWS, VAT, PAYMENTREF, TRACKTYPE, LOCTRACKING, TOOL, AUTOINCSL, DIVLOTSIZE, SHELFLIFE, SHELFDATE, DOMINANTREFS1, DOMINANTREFS2, DOMINANTREFS3, DOMINANTREFS4, DOMINANTREFS5, DOMINANTREFS6, DOMINANTREFS7, DOMINANTREFS8, DOMINANTREFS9, DOMINANTREFS10, DOMINANTREFS11, DOMINANTREFS12, IMAGEINC, TEXTINC, DEPRTYPE, DEPRRATE, DEPRDUR, SALVAGEVAL, REVALFLAG, REVDEPRFLAG, PARTDEP, DEPRTYPE2, DEPRRATE2, DEPRDUR2, REVALFLAG2, REVDEPRFLAG2, PARTDEP2, APPROVED, UNITSETREF, QCCSETREF, DISTAMOUNT, CAPIBLOCK_CREATEDBY, CAPIBLOCK_CREADEDDATE, CAPIBLOCK_CREATEDHOUR, CAPIBLOCK_CREATEDMIN, CAPIBLOCK_CREATEDSEC, CAPIBLOCK_MODIFIEDBY, CAPIBLOCK_MODIFIEDDATE, CAPIBLOCK_MODIFIEDHOUR, CAPIBLOCK_MODIFIEDMIN, CAPIBLOCK_MODIFIEDSEC, SITEID, RECSTATUS, ORGLOGICREF, UNIVID, DISTLOTUNITS, COMBLOTUNITS, WFSTATUS, DISTPOINT, CAMPPOINT, CANUSEINTRNS, ISONR, GROUPNR, PRODCOUNTRY, ADDTAXREF, QPRODAMNT, QPRODUOM, QPRODSRCINDEX, EXTACCESSFLAGS, PACKET, SALVAGEVAL2, SELLVAT, RETURNVAT, LOGOID, LIDCONFIRMED, GTIPCODE, EXPCTGNO, B2CCODE, MARKREF, IMAGE2INC, AVRWHDURATION, EXTCARDFLAGS, MINORDAMOUNT, FREIGHTPLACE, FREIGHTTYPCODE1, FREIGHTTYPCODE2, FREIGHTTYPCODE3, FREIGHTTYPCODE4, FREIGHTTYPCODE5, FREIGHTTYPCODE6, FREIGHTTYPCODE7, FREIGHTTYPCODE8, FREIGHTTYPCODE9, FREIGHTTYPCODE10, STATECODE, STATENAME, EXPCATEGORY, LOSTFACTOR, TEXTINCENG, EANBARCODE, DEPRCLASSTYPE, WFLOWCRDREF, SELLPRVAT, RETURNPRVAT, LOWLEVELCODES1, LOWLEVELCODES2, LOWLEVELCODES3, LOWLEVELCODES4, LOWLEVELCODES5, LOWLEVELCODES6, LOWLEVELCODES7, LOWLEVELCODES8, LOWLEVELCODES9, LOWLEVELCODES10, ORGLOGOID, QPRODDEPART, CANCONFIGURE, CHARSETREF, CANDEDUCT, CONSCODEREF, SPECODE2, SPECODE3, SPECODE4, SPECODE5, EXPENSE, ORIGIN, NAME2, COMPKDVUSE, USEDINPERIODS, EXIMTAX1, EXIMTAX2, EXIMTAX3, EXIMTAX4, EXIMTAX5, PRODUCTLEVEL, APPSPEVATMATRAH, NAME3, FACOSTKEYS, KKLINESDISABLE, APPROVE, APPROVEDATE, GLOBALID, SALEDEDUCTPART1, SALEDEDUCTPART2, PURCDEDUCTPART1, PURCDEDUCTPART2, CATEGORYID, CATEGORYNAME, KEYWORD1, KEYWORD2, KEYWORD3, KEYWORD4, KEYWORD5, GUID, DEMANDMEETSORTFLD1, DEMANDMEETSORTFLD2, DEMANDMEETSORTFLD3, DEMANDMEETSORTFLD4, DEMANDMEETSORTFLD5, DEDUCTCODE, PROJECTREF, NAME4, QPRODSUBAMNT, QPRODSUBUOM, QPRODSUBSRCINDEX, QPRODSUBDEPART , LOG_HOSTNAME, LOG_DATE, LOG_PROGRAM, LOG_USERNAME, LOG_SQL, ACTION_TYPE)
select 
LOGICALREF, ACTIVE, CARDTYPE, CODE, NAME, STGRPCODE, PRODUCERCODE, SPECODE, CYPHCODE, CLASSTYPE, PURCHBRWS, SALESBRWS, MTRLBRWS, VAT, PAYMENTREF, TRACKTYPE, LOCTRACKING, TOOL, AUTOINCSL, DIVLOTSIZE, SHELFLIFE, SHELFDATE, DOMINANTREFS1, DOMINANTREFS2, DOMINANTREFS3, DOMINANTREFS4, DOMINANTREFS5, DOMINANTREFS6, DOMINANTREFS7, DOMINANTREFS8, DOMINANTREFS9, DOMINANTREFS10, DOMINANTREFS11, DOMINANTREFS12, IMAGEINC, TEXTINC, DEPRTYPE, DEPRRATE, DEPRDUR, SALVAGEVAL, REVALFLAG, REVDEPRFLAG, PARTDEP, DEPRTYPE2, DEPRRATE2, DEPRDUR2, REVALFLAG2, REVDEPRFLAG2, PARTDEP2, APPROVED, UNITSETREF, QCCSETREF, DISTAMOUNT, CAPIBLOCK_CREATEDBY, CAPIBLOCK_CREADEDDATE, CAPIBLOCK_CREATEDHOUR, CAPIBLOCK_CREATEDMIN, CAPIBLOCK_CREATEDSEC, CAPIBLOCK_MODIFIEDBY, CAPIBLOCK_MODIFIEDDATE, CAPIBLOCK_MODIFIEDHOUR, CAPIBLOCK_MODIFIEDMIN, CAPIBLOCK_MODIFIEDSEC, SITEID, RECSTATUS, ORGLOGICREF, UNIVID, DISTLOTUNITS, COMBLOTUNITS, WFSTATUS, DISTPOINT, CAMPPOINT, CANUSEINTRNS, ISONR, GROUPNR, PRODCOUNTRY, ADDTAXREF, QPRODAMNT, QPRODUOM, QPRODSRCINDEX, EXTACCESSFLAGS, PACKET, SALVAGEVAL2, SELLVAT, RETURNVAT, LOGOID, LIDCONFIRMED, GTIPCODE, EXPCTGNO, B2CCODE, MARKREF, IMAGE2INC, AVRWHDURATION, EXTCARDFLAGS, MINORDAMOUNT, FREIGHTPLACE, FREIGHTTYPCODE1, FREIGHTTYPCODE2, FREIGHTTYPCODE3, FREIGHTTYPCODE4, FREIGHTTYPCODE5, FREIGHTTYPCODE6, FREIGHTTYPCODE7, FREIGHTTYPCODE8, FREIGHTTYPCODE9, FREIGHTTYPCODE10, STATECODE, STATENAME, EXPCATEGORY, LOSTFACTOR, TEXTINCENG, EANBARCODE, DEPRCLASSTYPE, WFLOWCRDREF, SELLPRVAT, RETURNPRVAT, LOWLEVELCODES1, LOWLEVELCODES2, LOWLEVELCODES3, LOWLEVELCODES4, LOWLEVELCODES5, LOWLEVELCODES6, LOWLEVELCODES7, LOWLEVELCODES8, LOWLEVELCODES9, LOWLEVELCODES10, ORGLOGOID, QPRODDEPART, CANCONFIGURE, CHARSETREF, CANDEDUCT, CONSCODEREF, SPECODE2, SPECODE3, SPECODE4, SPECODE5, EXPENSE, ORIGIN, NAME2, COMPKDVUSE, USEDINPERIODS, EXIMTAX1, EXIMTAX2, EXIMTAX3, EXIMTAX4, EXIMTAX5, PRODUCTLEVEL, APPSPEVATMATRAH, NAME3, FACOSTKEYS, KKLINESDISABLE, APPROVE, APPROVEDATE, GLOBALID, SALEDEDUCTPART1, SALEDEDUCTPART2, PURCDEDUCTPART1, PURCDEDUCTPART2, CATEGORYID, CATEGORYNAME, KEYWORD1, KEYWORD2, KEYWORD3, KEYWORD4, KEYWORD5, GUID, DEMANDMEETSORTFLD1, DEMANDMEETSORTFLD2, DEMANDMEETSORTFLD3, DEMANDMEETSORTFLD4, DEMANDMEETSORTFLD5, DEDUCTCODE, PROJECTREF, NAME4, QPRODSUBAMNT, QPRODSUBUOM, QPRODSUBSRCINDEX, QPRODSUBDEPART , @LOG_HOSTNAME, @LOG_DATE, @LOG_PROGRAM, @LOG_USERNAME, @LOG_SQL, @LOG_ACTIONTYPE
from deleted
end

delete from TIGER2.DBO.LG_217_ITEMS where CODE='85'
update TIGER2.DBO.LG_217_ITEMS set NAME=NAME+'deneme' where LOGICALREF=81

select * from LG_217_ITEMS
select * from TIGER2.dbo.LG_217_ITEMS where LOGICALREF='85'

truncate table LG_217_ITEMS