ALTER view VM_SATISLAR
as
select
ITM.CODE MALZEMEKODU,ITM.NAME MALZEMEADI,ITM.KEYWORD1 as MARKA,ITM.KEYWORD2 as KATEGORI1,ITM.KEYWORD3 as KATEGORI2,
STL.DATE_ TARIH,STL.AMOUNT MIKTAR,STL.PRICE FIYAT,STL.LINENET TUTAR,STF.BRANCH SUBENO,D.NAME as SUBEADI
from LG_217_ITEMS ITM

left join LG_217_01_STLINE STL on STL.STOCKREF=ITM.LOGICALREF
left join LG_217_01_STFICHE STF on STF.LOGICALREF=STL.STFICHEREF
left join L_CAPIDIV D on D.NR=STF.BRANCH and D.FIRMNR=217

where STL.TRCODE=7

update L_CAPIDIV set NAME=REPLACE(NAME,'?','Þ')

select * from VM_SATISLAR where BRAND='DR.OETKER'

select MARKA,sum(TUTAR) as TOTAL from VM_SATISLAR group by MARKA order by 2 desc

SELECT DATEPART(MONTH,TARIH) AS AY,SUM(TUTAR) AS TUTAR FROM VM_SATISLAR GROUP BY DATEPART(MONTH,TARIH) ORDER BY 2 DESC